name: general_knowledge
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  rflutter_alert: ^2.0.2
  url_launcher: ^6.0.3
  page_transition: "^2.0.2"
  flutter_dnd: ^0.1.3
  flip_card: ^0.5.0
  firebase_core: ^1.2.1
  flutter_rating_bar: ^4.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  firebase_auth: ^1.4.0
  shared_preferences: ^2.0.6
  cloud_firestore: ^2.2.1
  flutter_local_notifications: ^6.0.0
  firebase_messaging: ^10.0.2
  introduction_screen: ^2.1.0
  fluttertoast: ^8.0.7
  connectivity_plus: ^1.0.3
  animated_text_kit: ^4.1.1
  google_mobile_ads: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: coder
      fonts:
        - asset: assets/fonts/OdibeeSans-Regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf